Feature/serializable dictionary garbage free enumerator
FishingCactus/UnityCommonCode pull request #107
Opened 2024-04-08 16:45 UTC by lucas-baran

# Changelog

## [1.1.0] - 2024-02-29
### Added
- Add SerializableDictionaryEnumerable for readonly and garbage free iterating over dictionaries for properties
### Updated
- No more memory is allocated when iterating with a foreach loop over SerializableDictionary, or its Key or Value properties
  - This uses custom enumerators structs types which handle the enumeration
- No more memory is allocated when getting the keys and values collections of a SerializableDuctionary
  - This uses custom KeyCollection and ValueCollection types similarly to what is done in .NET dictionaries

# Usage
```Csharp
public class DictionaryHolder
{
    private SerializableDictionary<int, int> _dictionary;

    public SerializableDictionary<int, int> Dictionary => _dictionary;
    public SerializableDictionaryEnumerable<int, int> StructEnumerable => _dictionary;
    public IReadOnlyDictionary<int, int> ReadOnlyDictionary => _dictionary;
    public IEnumerable<KeyValuePair<int, int>> Enumerable => _dictionary;
    public ICollection<KeyValuePair<int, int>> Collection => _dictionary;

    public void Enumerate()
    {
        // allocates 0B of memory but dictionary can be modified
        foreach(var kvp in Dictionary) { }

        // allocates 0B of memory instead of 4KB before
        foreach(var kvp in Dictionary.Keys) { }

        // allocates 0B of memory instead of 4KB before
        foreach(var kvp in Dictionary.Values) { }

        // allocates 0B of memory while keeping readonly access to the dictionary (cannot be cast to SerializableDictionary)
        foreach(var kvp in StructEnumerableDictionary) { }

        // allocates 48B of memory while keeping partial readonly access to the dictionary (can be cast to SerializableDictionary)
        foreach(var kvp in ReadOnlyDictionary) { }

        // allocates 48B of memory while keeping partial readonly access to the dictionary (can be cast to SerializableDictionary)
        foreach(var kvp in EnumerableDictionary) { }

        // allocates 48B of memory while keeping partial readonly access to the dictionary (can be cast to SerializableDictionary)
        foreach(var kvp in CollectionDictionary) { }
    }
}
```

2024-04-09 08:31 UTC, rascar-capac requested changes
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @fishingcactus-nathan-istace, @LeanderSimonart, @LouisNillusFC, @lucas-baran, @MaxDaniels, @PetitT, @Skeloson, @TheEmidee, and @ThibNach)

___
*[`Runtime/Helpers/ThrowHelper.cs` line 31 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0psd7C16m2GNWB1m4:-Nv0psd7C16m2GNWB1m5:bc1rhi) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Helpers/ThrowHelper.cs#L31)):*
> ```Smalltalk
>             )
>         {
>             if( index < 0 || index >= count )
> ```

condition on multiple lines
___
*[`Runtime/Utils/SerializableDictionary.cs` line 151 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0vd-Y7aOKDJjZCNqh:-Nv0vd-Y7aOKDJjZCNqi:b-n9p4ay) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L151)):*
> ```Smalltalk
>         }
> 
>         #region IDictionary
> ```

Regions were largely disapproved in the cs poll, maybe it would be better to remove them?
___
*[`Runtime/Utils/SerializableDictionary.cs` line 316 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0xwGy4J0F7VWcXUj0:-Nv0xeB6ECwEoKWtJKXU:b7kul28) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L316)):*
> ```Smalltalk
>                     {
>                         throw new InvalidOperationException( ThrowHelper.ENUMERATION_CANNOT_HAPPEN );
>                     }
> ```

why not use `ThrowHelper.ThrowIfArgumentOutOfRange`?
___
*[`Runtime/Utils/SerializableDictionary.cs` line 329 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0y3-A4bj628-O_fCw:-Nv0y3-A4bj628-O_fCx:b7kul28) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L329)):*
> ```Smalltalk
>                     {
>                         throw new InvalidOperationException( ThrowHelper.ENUMERATION_CANNOT_HAPPEN );
>                     }
> ```

why not use `ThrowHelper.ThrowIfArgumentOutOfRange`?
___
*[`Runtime/Utils/SerializableDictionary.cs` line 342 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0y3Xc1vdL6IShRk8U:-Nv0y3Xc1vdL6IShRk8V:b7kul28) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L342)):*
> ```Smalltalk
>                     {
>                         throw new InvalidOperationException( ThrowHelper.ENUMERATION_CANNOT_HAPPEN );
>                     }
> ```

why not use `ThrowHelper.ThrowIfArgumentOutOfRange`?
___
*[`Runtime/Utils/SerializableDictionary.cs` line 355 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0y3vk1MzTN4WPXIIg:-Nv0y3vk1MzTN4WPXIIh:b7kul28) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L355)):*
> ```Smalltalk
>                     {
>                         throw new InvalidOperationException( ThrowHelper.ENUMERATION_CANNOT_HAPPEN );
>                     }
> ```

why not use `ThrowHelper.ThrowIfArgumentOutOfRange`?
___
*[`Runtime/Utils/SerializableDictionary.cs` line 794 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0udfn1Ai3DEvWxmjy:-Nv0udfn1Ai3DEvWxmjz:bc1rhi) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L794)):*
> ```Smalltalk
>                     get
>                     {
>                         if( _currentIndex == 0 || _currentIndex == _dictionary.Count + 1 )
> ```

condition on multiple lines


<!-- Sent from Reviewable.io -->

2024-04-09 10:19 UTC, LouisNillusFC requested changes
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107)* status: all files reviewed, 15 unresolved discussions (waiting on @fishingcactus-nathan-istace, @LeanderSimonart, @lucas-baran, @MaxDaniels, @PetitT, @Skeloson, @TheEmidee, and @ThibNach)

___
*[`Runtime/Utils/SerializableDictionary.cs` line 63 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1Kaz5E4HLeRwHWFbx:-Nv1Kaz5E4HLeRwHWFby:b-5cpifw) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L63)):*
> ```Smalltalk
>         public bool IsReadOnly => false;
> 
>         ICollection<TKey> IDictionary<TKey, TValue>.Keys => Keys;
> ```

Explicit protection level
___
*[`Runtime/Utils/SerializableDictionary.cs` line 422 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1I4ptDkqEY3ZI2GZy:-Nv1I4ptDkqEY3ZI2GZz:bqmsmco) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L422)):*
> ```Smalltalk
>             {
>                 return index >= 0
>                     || index < _dictionary.Count;
> ```

Isn't it on one line when we have a return ?
___
*[`Runtime/Utils/SerializableDictionary.cs` line 436 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1KS5V8tp2XJQOemX4:-Nv1KS5V8tp2XJQOemX5:b-5cpifw) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L436)):*
> ```Smalltalk
>             public int Count => _dictionary.Count;
> 
>             bool ICollection<TKey>.IsReadOnly => true;
> ```

Explicit protection level
___
*[`Runtime/Utils/SerializableDictionary.cs` line 468 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1Ip_o7HjK4S0SAE8m:-Nv1Ip_o7HjK4S0SAE8n:b-hfj1em) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L468)):*
> ```Smalltalk
>                 if( array.Length - index < _dictionary.Count )
>                 {
>                     throw new ArgumentException( "Array is too small for copy" );
> ```

Can't you put that one in the ThrowHelper ?
___
*[`Runtime/Utils/SerializableDictionary.cs` line 581 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1JZxcDrPyUS1iTiUO:-Nv1JZxcDrPyUS1iTiUP:b-emhv8z) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L581)):*
> ```Smalltalk
>                     get
>                     {
>                         if( _currentIndex == 0 || _currentIndex == _dictionary.Count + 1 )
> ```

Conditions on multiple lines
___
*[`Runtime/Utils/SerializableDictionary.cs` line 649 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1KCg43d30ic9g5Uzk:-Nv1KCg43d30ic9g5Uzl:b-5cpifw) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L649)):*
> ```Smalltalk
>             public int Count => _dictionary.Count;
> 
>             bool ICollection<TValue>.IsReadOnly => true;
> ```

Explicit protection level
___
*[`Runtime/Utils/SerializableDictionary.cs` line 762 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1KiK29tJ-H4DewToI:-Nv1KiK29tJ-H4DewToJ:bt006ng) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L762)):*
> ```Smalltalk
>                     try
>                     {
> ```

empty line
___
*[`Runtime/Utils/SerializableDictionary.cs` line 841 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1MRt57uofT-BqvIQ8:-Nv1MRt57uofT-BqvIQ9:b91pgpt) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L841)):*
> ```Smalltalk
>                     for( ; _currentIndex < _dictionary.KeyValueList.Count; _currentIndex++ )
>                     {
>                         _currentKey = _dictionary.KeyValueList[ _currentIndex ].Value;
> ```

missing return true ^^


<!-- Sent from Reviewable.io -->

2024-04-10 08:26 UTC, lucas-baran reviewed
I added other structs for readonly access and garbage free enumerators, and also made them implement IEnumerable so they can be used with Linq (though using Linq is not garbage free but it can still be useful).
These structs allow for readonly access over common collection types and provide garbage free enumeration. Knowing that, would it be better to rename the "EnumerableThing" structs to "ReadOnlyThing" (EnumerableList would become ReadOnlyList)?

> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-:-Nv64r4N501EnajHfcDL:b-59crr1)* status: all files reviewed, 14 unresolved discussions (waiting on @fishingcactus-nathan-istace, @LeanderSimonart, @LouisNillusFC, @MaxDaniels, @PetitT, @rascar-capac, @Skeloson, @TheEmidee, and @ThibNach)

___
*[`Runtime/Helpers/ThrowHelper.cs` line 31 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0psd7C16m2GNWB1m4:-Nv5wrDO7WUY-yGkWqfN:b-896fix) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Helpers/ThrowHelper.cs#L31)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

condition on multiple lines
</blockquote></details>

Done.
___
*[`Runtime/Utils/SerializableDictionary.cs` line 63 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1Kaz5E4HLeRwHWFbx:-Nv5wRB5AdvJx67ndCE2:b973o7x) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L63)):*
<details><summary><i>Previously, LouisNillusFC wrote…</i></summary><blockquote>

Explicit protection level
</blockquote></details>

Not possible, this is an explicit interface implementation
___
*[`Runtime/Utils/SerializableDictionary.cs` line 151 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0vd-Y7aOKDJjZCNqh:-Nv5wbdBAcSV_nqT2G1i:b-896fix) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L151)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

Regions were largely disapproved in the cs poll, maybe it would be better to remove them?
</blockquote></details>

Done.
___
*[`Runtime/Utils/SerializableDictionary.cs` line 316 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0xwGy4J0F7VWcXUj0:-Nv5xE-S8YJ0gSBZYN4S:b-fy8yoe) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L316)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

why not use `ThrowHelper.ThrowIfArgumentOutOfRange`?
</blockquote></details>

This is not an IndexOutOfRangeException
___
*[`Runtime/Utils/SerializableDictionary.cs` line 329 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0y3-A4bj628-O_fCw:-Nv5xNtk82yoP_yPFnLW:b-fy8yoe) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L329)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

why not use `ThrowHelper.ThrowIfArgumentOutOfRange`?
</blockquote></details>

This is not an IndexOutOfRangeException
___
*[`Runtime/Utils/SerializableDictionary.cs` line 342 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0y3Xc1vdL6IShRk8U:-Nv5xOzV-3jItw2uAmbu:b-fy8yoe) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L342)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

why not use `ThrowHelper.ThrowIfArgumentOutOfRange`?
</blockquote></details>

This is not an IndexOutOfRangeException
___
*[`Runtime/Utils/SerializableDictionary.cs` line 355 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0y3vk1MzTN4WPXIIg:-Nv5xPX-7gz-Fl5NRNtL:b-fy8yoe) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L355)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

why not use `ThrowHelper.ThrowIfArgumentOutOfRange`?
</blockquote></details>

This is not an IndexOutOfRangeException
___
*[`Runtime/Utils/SerializableDictionary.cs` line 422 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1I4ptDkqEY3ZI2GZy:-Nv5xVIi8zs2rjVkSTPy:bc4k9gi) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L422)):*
<details><summary><i>Previously, LouisNillusFC wrote…</i></summary><blockquote>

Isn't it on one line when we have a return ?
</blockquote></details>

I don't know, we do it a lot on Corsairs
___
*[`Runtime/Utils/SerializableDictionary.cs` line 436 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1KS5V8tp2XJQOemX4:-Nv5xTNu3CVmjS-BU48Q:b973o7x) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L436)):*
<details><summary><i>Previously, LouisNillusFC wrote…</i></summary><blockquote>

Explicit protection level
</blockquote></details>

Not possible, this is an explicit interface implementation
___
*[`Runtime/Utils/SerializableDictionary.cs` line 468 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1Ip_o7HjK4S0SAE8m:-Nv5x_R611i8M01uYVCR:bl3cr2l) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L468)):*
<details><summary><i>Previously, LouisNillusFC wrote…</i></summary><blockquote>

Can't you put that one in the ThrowHelper ?
</blockquote></details>

The condition is a bit too specific
___
*[`Runtime/Utils/SerializableDictionary.cs` line 581 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1JZxcDrPyUS1iTiUO:-Nv5xdBK3HlNUKzK5QE-:b-896fix) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L581)):*
<details><summary><i>Previously, LouisNillusFC wrote…</i></summary><blockquote>

Conditions on multiple lines
</blockquote></details>

Done.
___
*[`Runtime/Utils/SerializableDictionary.cs` line 649 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1KCg43d30ic9g5Uzk:-Nv5xp4E5hv702NuoaU1:b973o7x) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L649)):*
<details><summary><i>Previously, LouisNillusFC wrote…</i></summary><blockquote>

Explicit protection level
</blockquote></details>

Not possible, this is an explicit interface implementation
___
*[`Runtime/Utils/SerializableDictionary.cs` line 762 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1KiK29tJ-H4DewToI:-Nv5xqOnC4Mrewl2vzYu:b-896fix) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L762)):*
<details><summary><i>Previously, LouisNillusFC wrote…</i></summary><blockquote>

empty line
</blockquote></details>

Done.
___
*[`Runtime/Utils/SerializableDictionary.cs` line 794 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv0udfn1Ai3DEvWxmjy:-Nv5xvVK2JcWgJwKOyng:b-896fix) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L794)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

condition [...]

2024-04-10 08:52 UTC, rascar-capac approved these changes
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107)* status: all files reviewed, 11 unresolved discussions (waiting on @fishingcactus-nathan-istace, @LeanderSimonart, @LouisNillusFC, @lucas-baran, @MaxDaniels, @PetitT, @Skeloson, @TheEmidee, and @ThibNach)

___
*[`Runtime/Utils/SerializableDictionary.cs` line 422 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1I4ptDkqEY3ZI2GZy:-Nv68WySBzmqpqu0wSI8:bt9q0tv) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L422)):*
<details><summary><i>Previously, lucas-baran (Lucas Baran) wrote…</i></summary><blockquote>

I don't know, we do it a lot on Corsairs
</blockquote></details>

yes I do it as well. But we won't probably do it anymore when new cs are validated
___
*[`Runtime/Utils/SerializableDictionary.cs` line 381 at r2](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv68K3PAPIkHs1GA3Tq:-Nv68K3PAPIkHs1GA3Tr:b-gtq12h) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/44e5e0af5d5bf30ba2e3837ce92a7debd9ff6da8/Runtime/Utils/SerializableDictionary.cs#L381)):*
> ```Smalltalk
>                 }
> 
>                 for( ; _currentIndex < _dictionary.KeyValueList.Count; )
> ```

a while would be more readable at this point
___
*[`Runtime/Utils/SerializableDictionary.cs` line 621 at r2](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv69-U6EOAVhb2_PP9B:-Nv69-U6EOAVhb2_PP9C:b-5lg81l) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/44e5e0af5d5bf30ba2e3837ce92a7debd9ff6da8/Runtime/Utils/SerializableDictionary.cs#L621)):*
> ```Smalltalk
>                     }
> 
>                     for( ; _currentIndex < _dictionary.KeyValueList.Count; )
> ```

while loop?
___
*[`Runtime/Utils/SerializableDictionary.cs` line 838 at r2](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv694gMBF76LHfnoQ1t:-Nv694gMBF76LHfnoQ1u:b-5lg81l) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/44e5e0af5d5bf30ba2e3837ce92a7debd9ff6da8/Runtime/Utils/SerializableDictionary.cs#L838)):*
> ```Smalltalk
>                     }
> 
>                     for( ; _currentIndex < _dictionary.KeyValueList.Count; )
> ```

while loop?


<!-- Sent from Reviewable.io -->

2024-04-10 08:53 UTC, LouisNillusFC approved these changes
> Reviewed 3 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107)* status: all files reviewed, 5 unresolved discussions (waiting on @fishingcactus-nathan-istace, @LeanderSimonart, @lucas-baran, @MaxDaniels, @PetitT, @rascar-capac, @Skeloson, @TheEmidee, and @ThibNach)

___
*[`Runtime/Utils/SerializableDictionary.cs` line 422 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1I4ptDkqEY3ZI2GZy:-Nv6Ad3zD3gt0iCyRUrU:bjytgtt) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L422)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

yes I do it as well. But we won't probably do it anymore when new cs are validated
</blockquote></details>

I haven't seen it that much so far, but it doesn't matter much anyway
___
*[`Runtime/Utils/SerializableDictionary.cs` line 468 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv1Ip_o7HjK4S0SAE8m:-Nv69x7FAlDHsCiE0sFm:b-7oownj) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/7818f1abd9df87beeed69450a143ee9bc0dc3edf/Runtime/Utils/SerializableDictionary.cs#L468)):*
<details><summary><i>Previously, lucas-baran (Lucas Baran) wrote…</i></summary><blockquote>

The condition is a bit too specific
</blockquote></details>

Still it's used twice


<!-- Sent from Reviewable.io -->

2024-04-10 08:57 UTC, rascar-capac approved these changes
I agree with the renaming

> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-:-Nv6Cb82-Wbw3biKKdK7:b5k2e2c)* status: all files reviewed, 5 unresolved discussions (waiting on @fishingcactus-nathan-istace, @LeanderSimonart, @lucas-baran, @MaxDaniels, @PetitT, @Skeloson, @TheEmidee, and @ThibNach)



<!-- Sent from Reviewable.io -->

2024-04-10 15:16 UTC, TheEmidee approved these changes
> Reviewed 4 of 8 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107)* status: all files reviewed, 5 unresolved discussions (waiting on @fishingcactus-nathan-istace, @LeanderSimonart, @lucas-baran, @MaxDaniels, @PetitT, @rascar-capac, @Skeloson, and @ThibNach)



<!-- Sent from Reviewable.io -->

2024-04-11 05:45 UTC, Skeloson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-:-NvAgBiJ5P22lXATj5Tp:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @fishingcactus-nathan-istace, @LeanderSimonart, @lucas-baran, @MaxDaniels, @PetitT, @rascar-capac, and @ThibNach)



<!-- Sent from Reviewable.io -->

2024-04-11 07:45 UTC, PetitT approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107)* status: all files reviewed, 5 unresolved discussions (waiting on @fishingcactus-nathan-istace, @LeanderSimonart, @lucas-baran, @MaxDaniels, @rascar-capac, and @ThibNach)



<!-- Sent from Reviewable.io -->

2024-04-11 07:59 UTC, MaxDaniels approved these changes
> Reviewed 5 of 8 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107)* status: all files reviewed, 5 unresolved discussions (waiting on @fishingcactus-nathan-istace, @LeanderSimonart, @lucas-baran, @rascar-capac, and @ThibNach)



<!-- Sent from Reviewable.io -->

2024-04-11 08:31 UTC, lucas-baran reviewed
I updated the structs:
- added the missing FishingCactus namespace
- renamed them to "[Collection]Enumerable" to "ReadOnly[Collection]"

> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-:-NvBEvuTDKd6pmZTN7V0:be67w5v)* status: 4 of 18 files reviewed, all discussions resolved (waiting on @fishingcactus-nathan-istace, @LeanderSimonart, @LouisNillusFC, @MaxDaniels, @rascar-capac, @TheEmidee, and @ThibNach)

___
*[`Runtime/Utils/SerializableDictionary.cs` line 381 at r2](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv68K3PAPIkHs1GA3Tq:-NvBGfLHAff2L1t-n8S1:b-896fix) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/44e5e0af5d5bf30ba2e3837ce92a7debd9ff6da8/Runtime/Utils/SerializableDictionary.cs#L381)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

a while would be more readable at this point
</blockquote></details>

Done.
___
*[`Runtime/Utils/SerializableDictionary.cs` line 621 at r2](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv69-U6EOAVhb2_PP9B:-NvBFlL71BALYnyE2ehU:b-896fix) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/44e5e0af5d5bf30ba2e3837ce92a7debd9ff6da8/Runtime/Utils/SerializableDictionary.cs#L621)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

while loop?
</blockquote></details>

Done.
___
*[`Runtime/Utils/SerializableDictionary.cs` line 838 at r2](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-Nv694gMBF76LHfnoQ1t:-NvBGdIt6_0sBncytkA2:b-896fix) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/44e5e0af5d5bf30ba2e3837ce92a7debd9ff6da8/Runtime/Utils/SerializableDictionary.cs#L838)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

while loop?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-11 08:44 UTC, LeanderSimonart approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 8 files at r1, 1 of 14 files at r2, 14 of 15 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-:-NvBK0F8AxDu9_GA8qaM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fishingcactus-nathan-istace and @ThibNach)



<!-- Sent from Reviewable.io -->

2024-04-11 11:46 UTC, fishingcactus-nathan-istace commented
*[`Runtime/Helpers/ThrowHelper.cs` line 5 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvByD3P-_fRn93zaIVn:-NvByD3P-_fRn93zaIVo:b-uoo8j6) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Helpers/ThrowHelper.cs#L5)):*
> ```Smalltalk
> namespace FishingCactus
> {
>     public class ThrowHelper
> ```

class can be static


<!-- Sent from Reviewable.io -->

2024-04-11 11:48 UTC, fishingcactus-nathan-istace commented
*[`Runtime/Helpers/ThrowHelper.cs` line 25 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvBynux1GUX2MaKn-AD:-NvBynux1GUX2MaKn-AE:b-sc83il) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Helpers/ThrowHelper.cs#L25)):*
> ```Smalltalk
>         }
> 
>         public static void ThrowIfArgumentOutOfRange(
> ```

I'd expect to be able to provide a range in a function that talks about range. If it's always a value between 0 and a length/count, wouldn't IndexOutOfBounds make more sense?


<!-- Sent from Reviewable.io -->

2024-04-11 12:07 UTC, fishingcactus-nathan-istace commented
*[`Runtime/Utils/ReadOnlyCollections/ReadOnlyDictionary.cs` line 6 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvC2M-cCHzx7YBJVxO0:-NvC2M-cCHzx7YBJVxO1:bwqqhu7) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Utils/ReadOnlyCollections/ReadOnlyDictionary.cs#L6)):*
> ```Smalltalk
> namespace FishingCactus
> {
>     public readonly struct ReadOnlyDictionary<TKey, TValue> : IEnumerable<KeyValuePair<TKey, TValue>>, IReadOnlyCollection<KeyValuePair<TKey, TValue>>
> ```

IEnumerable inherits from IReadOnlyCollection, it doesn't need to be mentioned.


<!-- Sent from Reviewable.io -->

2024-04-11 12:09 UTC, fishingcactus-nathan-istace commented
*[`Runtime/Utils/ReadOnlyCollections/ReadOnlyHashSet.cs` line 6 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvC2taO0Wyp_fWJSy97:-NvC2taP32QEsMKh-D3a:bd2vazs) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Utils/ReadOnlyCollections/ReadOnlyHashSet.cs#L6)):*
> ```Smalltalk
> namespace FishingCactus
> {
>     public readonly struct ReadOnlyHashSet<T> : IEnumerable<T>, IReadOnlyCollection<T>
> ```

Same comment about IEnumerable and IReadOnlyCollection


<!-- Sent from Reviewable.io -->

2024-04-11 12:14 UTC, fishingcactus-nathan-istace commented
*[`Runtime/Utils/ReadOnlyCollections/ReadOnlyList.cs` line 7 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvC41qKEFOIH40-amBV:-NvC41qKEFOIH40-amBW:bjpg0in) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Utils/ReadOnlyCollections/ReadOnlyList.cs#L7)):*
> ```Smalltalk
> namespace FishingCactus
> {
>     public readonly struct ReadOnlyList<T> : IEnumerable<T>, IReadOnlyCollection<T>
> ```

I would assume this implements IReadOnlyList<T>. Doing so, IEnumerable and IReadOnlyCollection can be removed, as they both extend IReadOnlyList


<!-- Sent from Reviewable.io -->

2024-04-11 12:17 UTC, fishingcactus-nathan-istace commented
*[`Runtime/Utils/ReadOnlyCollections/ReadOnlySerializableDictionary.cs` line 6 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvC4lsc6Y4TNZvAfk9i:-NvC4lsc6Y4TNZvAfk9j:b5vxk67) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Utils/ReadOnlyCollections/ReadOnlySerializableDictionary.cs#L6)):*
> ```Smalltalk
> namespace FishingCactus
> {
>     public readonly struct ReadOnlySerializableDictionary<TKey, TValue> : IEnumerable<KeyValuePair<TKey, TValue>>, IReadOnlyCollection<KeyValuePair<TKey, TValue>>
> ```

implement IReadOnlyDictionary


<!-- Sent from Reviewable.io -->

2024-04-11 12:19 UTC, fishingcactus-nathan-istace requested changes
> Reviewed 2 of 8 files at r1, 1 of 14 files at r2, 14 of 15 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107)* status: all files reviewed, 3 unresolved discussions (waiting on @lucas-baran and @ThibNach)



<!-- Sent from Reviewable.io -->

2024-04-11 12:50 UTC, MaxDaniels approved these changes
> Reviewed 14 of 15 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107)* status: all files reviewed, 4 unresolved discussions (waiting on @lucas-baran and @ThibNach)

___
*[`Runtime/Utils/SerializableDictionary.cs` line 255 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvCBu3B5TUhkYLXQcWJ:-NvCBu3B5TUhkYLXQcWK:bgezlhw) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Utils/SerializableDictionary.cs#L255)):*
> ```Smalltalk
>         public void CopyTo(
>             KeyValuePair<TKey,
>             TValue>[] array,
> ```

no need of a new line 


<!-- Sent from Reviewable.io -->

2024-04-11 13:29 UTC, lucas-baran reviewed
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107)* status: all files reviewed, 4 unresolved discussions (waiting on @fishingcactus-nathan-istace, @MaxDaniels, and @ThibNach)

___
*[`Runtime/Helpers/ThrowHelper.cs` line 5 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvByD3P-_fRn93zaIVn:-NvCIj7e-5ja_-Olob9r:bd30ifx) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Helpers/ThrowHelper.cs#L5)):*
<details><summary><i>Previously, fishingcactus-nathan-istace (NathanIstace) wrote…</i></summary><blockquote>

class can be static
</blockquote></details>

good catch
___
*[`Runtime/Helpers/ThrowHelper.cs` line 25 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvBynux1GUX2MaKn-AD:-NvCIrA94OEOeu8SRyZH:bhgt9tm) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Helpers/ThrowHelper.cs#L25)):*
<details><summary><i>Previously, fishingcactus-nathan-istace (NathanIstace) wrote…</i></summary><blockquote>

I'd expect to be able to provide a range in a function that talks about range. If it's always a value between 0 and a length/count, wouldn't IndexOutOfBounds make more sense?
</blockquote></details>

It is named after the exception which is `ArgumentOutOfRangeException` (there is no `ArgumentOutOfBoundsException`), which is the one used when an index is out of the bounds of a collection. I was thinking about having a start_index too but it feels odd to always specify it to be 0, and it's also odd to specify it after the count parameter. In the end my best bet is to add an overload with the start_index
___
*[`Runtime/Utils/SerializableDictionary.cs` line 255 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvCBu3B5TUhkYLXQcWJ:-NvCK5wMD3Tp18avtSCQ:b-896fix) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Utils/SerializableDictionary.cs#L255)):*
<details><summary><i>Previously, MaxDaniels wrote…</i></summary><blockquote>

no need of a new line
</blockquote></details>

Done.
___
*[`Runtime/Utils/ReadOnlyCollections/ReadOnlyDictionary.cs` line 6 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvC2M-cCHzx7YBJVxO0:-NvCKISl17JtKbiYlo5t:b-44flzp) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Utils/ReadOnlyCollections/ReadOnlyDictionary.cs#L6)):*
<details><summary><i>Previously, fishingcactus-nathan-istace (NathanIstace) wrote…</i></summary><blockquote>

IEnumerable inherits from IReadOnlyCollection, it doesn't need to be mentioned.
</blockquote></details>

It now implements `IReadOnlyDictionary` instead
___
*[`Runtime/Utils/ReadOnlyCollections/ReadOnlyHashSet.cs` line 6 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvC2taO0Wyp_fWJSy97:-NvCKZ115cEcpl0OCruS:b-yzxlxj) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Utils/ReadOnlyCollections/ReadOnlyHashSet.cs#L6)):*
<details><summary><i>Previously, fishingcactus-nathan-istace (NathanIstace) wrote…</i></summary><blockquote>

Same comment about IEnumerable and IReadOnlyCollection
</blockquote></details>

I like things to be explicit but it's indeed not needed
___
*[`Runtime/Utils/ReadOnlyCollections/ReadOnlyList.cs` line 7 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvC41qKEFOIH40-amBV:-NvCKji50aHdWq-RX0L4:b-896fix) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Utils/ReadOnlyCollections/ReadOnlyList.cs#L7)):*
<details><summary><i>Previously, fishingcactus-nathan-istace (NathanIstace) wrote…</i></summary><blockquote>

I would assume this implements IReadOnlyList<T>. Doing so, IEnumerable and IReadOnlyCollection can be removed, as they both extend IReadOnlyList
</blockquote></details>

Done.
___
*[`Runtime/Utils/ReadOnlyCollections/ReadOnlySerializableDictionary.cs` line 6 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvC4lsc6Y4TNZvAfk9i:-NvCKkuj4pwW6VPs29DL:b-896fix) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Utils/ReadOnlyCollections/ReadOnlySerializableDictionary.cs#L6)):*
<details><summary><i>Previously, fishingcactus-nathan-istace (NathanIstace) wrote…</i></summary><blockquote>

implement IReadOnlyDictionary
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-11 13:32 UTC, TheEmidee approved these changes
> Reviewed 8 of 15 files at r3, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107)* status: all files reviewed, 4 unresolved discussions (waiting on @fishingcactus-nathan-istace, @MaxDaniels, and @ThibNach)



<!-- Sent from Reviewable.io -->

2024-04-11 14:01 UTC, fishingcactus-nathan-istace commented
*[`Runtime/Helpers/ThrowHelper.cs` line 25 at r4](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107#-NvBynux1GUX2MaKn-AD:-NvCSHFe2m8z9npN_s5b:bwf7lfj) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/51936df81ae0e9020aafa218bcaeab94652cb26f/Runtime/Helpers/ThrowHelper.cs#L25)):*
<details><summary><i>Previously, lucas-baran (Lucas Baran) wrote…</i></summary><blockquote>

It is named after the exception which is `ArgumentOutOfRangeException` (there is no `ArgumentOutOfBoundsException`), which is the one used when an index is out of the bounds of a collection. I was thinking about having a start_index too but it feels odd to always specify it to be 0, and it's also odd to specify it after the count parameter. In the end my best bet is to add an overload with the start_index
</blockquote></details>

Ok, I was thinking of IndexOutOfBoundsException but I guess that's Java :D My bad!


<!-- Sent from Reviewable.io -->

2024-04-11 14:02 UTC, fishingcactus-nathan-istace approved these changes
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/107)* status: all files reviewed, 1 unresolved discussion (waiting on @MaxDaniels and @ThibNach)



<!-- Sent from Reviewable.io -->

2024-04-11 14:33 UTC, merged